using System;
using System.Reflection;
using System.Diagnostics;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Linq;

using Barotrauma;
using BaroJunk;

namespace BaroJunk.ComponentModules
{
  public partial class ConnectModules_Parts_Problem
  {
    public class ModuleA : IModule
    {
      [In] public ModuleB ModuleB { get; set; }
    }

    public class ModuleB : IModule
    {

    }

    /// <summary>
    /// This can't be autogenerated because only i can tell how parts should be organized
    /// </summary>
    public partial class Component
    {
      public class Component_Part : IPart { public Component Self { get; set; } }

      public class Secret_Part : Component_Part
      {
        public ModuleB ModuleB { get; set; } = new();
      }
    }

    public partial class Component : IComponent
    {
      private ModuleA ModuleA { get; } = new();
      private Secret_Part Secret { get; } = new();

      /// <summary>
      /// this should be generated
      /// </summary>
      private void ConnectParts()
      {
        Secret.Self = this;
      }

      /// <summary>
      /// this should be generated
      /// </summary>
      private void Connect()
      {
        ModuleA.ModuleB = Secret.ModuleB;
      }

      public Component()
      {
        Connect();
      }
    }

    public void Run()
    {

    }
  }
}