using System;
using System.Reflection;
using System.Diagnostics;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Linq;

using Barotrauma;
using System.Runtime.CompilerServices;

namespace BaroJunk
{

  public class ComponentModulesTest : UTestPack
  {

    public class ModuleA : IModule
    {
      public Component Host { get; set; }
      public string PropA => Host.Name;
    }

    public class ModuleB : IModule
    {
      [ModuleDependency] public ModuleA ModuleA { get; set; }

      public string GetPropA() => ModuleA.PropA;
    }

    public class ModuleC : IModule { }

    public class Component : IComponent
    {
      public string Name { get; set; } = "bruh";
      public class NestedWrapper : IModuleContainer
      {
        public ModuleB ModuleB { get; set; } = new();
        public ModuleC ModuleC { get; set; } = new();
      }

      public NestedWrapper Modules { get; } = new();

      [Module]
      public ModuleA ModuleA { get; set; } = new();

      public ModuleC ModuleC { get; set; } = new();

      [MethodImpl(MethodImplOptions.NoInlining)]
      public void InjectModules()
      {

        ModuleCodeGenerator.GenerateInjectCodeHere();
        //================> Autogenerated <================
        ModuleA.Host = this;
        Modules.ModuleB.ModuleA = ModuleA;
        //================< Autogenerated >================

      }
    }

    public override void CreateTests()
    {
      Component component = new();
      component.InjectModules();
      ModuleInjector.InjectModules(component);

      Tests.Add(new UTest(component.Modules.ModuleB.GetPropA(), "bruh"));

      Tests.Add(new UListTest(
        ModuleCodeGenerator.GenerateInjectCode(component).ToList(),
        new List<string>()
        {
          "ModuleA.Host = this;",
          "Modules.ModuleB.ModuleA = ModuleA;",
        }
      ));


    }
  }
}